# Generated by Django 3.1.12 on 2022-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
