# Generated by Django 4.0.4 on 2022-06-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20220521_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='leadership_position',
            field=models.CharField(choices=[('Elder', 'Elder'), ('Chairperson', 'Chairperson'), ('Decon', 'Decon'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member'), ('Pastor', 'Pastor')], max_length=25),
        ),
    ]
