# Generated by Django 3.1 on 2022-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_members_leadership_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='leadership_position',
            field=models.CharField(choices=[('Elder', 'Elder'), ('Leader', 'Leader'), ('Chairperson', 'Chairperson'), ('Decon', 'Decon'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Member', 'Member'), ('Pastor', 'Pastor')], max_length=25),
        ),
    ]
