# Generated by Django 4.0.4 on 2022-06-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0003_alter_members_leadership_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting_Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=12)),
                ('commission', models.CharField(choices=[("Women's Fellowship", "Women's Fellowship"), ("Men's Fellowship", "Men's Fellowship"), ("Youth's Fellowship", "Youth's Fellowship"), ("Children's Ministry", "Children's Ministry"), ("Couple's Ministry", "Couple's Ministry"), ('Widows and Singles Ministry', 'Widows and Singles Ministry'), ('Intercession Team', 'Intercession Team'), ('Building Commission', 'Building Commission'), ('Fundraising Commission', 'Fundraising Commission'), ('Ushering Commision', 'Ushering Commision'), ('Praise Team', 'Praise Team'), ('Evangelism and Outreach Commission', 'Evangelism and Outreach Commission'), ('Health Commission', 'Health Commission'), ('Finance Commission', 'Finance Commission'), ('Pastor and Wife', 'Pastor and Wife'), ('Elders', 'Elders'), ('Decons and Deconnesses', 'Decons and Deconnesses')], max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('has_won', models.BooleanField(default=False)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_vote', to='Management.members')),
            ],
        ),
    ]
